version: "2.2"
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
  server:
    build: ./
    ports:
      - "127.0.0.1:8080:8080"
    expose:
      - "8080"
    depends_on:
      - postgres
    networks:
      - default
